config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users
  get 'home/index'
  root 'tweets#index'
  get 'home/users'
  get '/(:item)', to: "home#user_tweets", as: 'user_tweets'
  
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :description,  presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweet
  validates :user_name,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @whatevs = User.find_by(id: current_user)  
  end
  
  def users
    @users = User.order(:user_name)
    @tweets = Tweet.all
  end
  
  def user_tweets
    @item = params['item']
    @whatevs = User.find_by(user_name: @item)  
    @tweets = Tweet.all
    @users = User.all
    
  end
  

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @namer = User.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @namer = User.all
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @users_id = User.new
    
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:description, :user_name, :user_id, :email, :id)
    end
    
    def correct_user
      @tweet = current_user.tweet.find_by(id: params[:id])
      redirect_to tweets_path, notice: "Not authorized to edit this tweet - and you know it!" if @tweet.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/_flash_alerts.html.erb
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

app/views/home/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Twitterly", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if user_signed_in? %>
          <li><a href="/<%= current_user.user_name %>">Your Tweets</a></li>
          <li><%= link_to "Show All Tweets", tweets_path %></li>
          <li><%= link_to "New Tweet", new_tweet_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "List Users", home_users_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
Hello World!

<% if user_signed_in? %>
    <%= @whatevs.user_name %>
<% end %>

app/views/home/user_tweets.html.erb
<h1><%= @item.titleize %>'s Tweets</h1>
<ul>
<% @whatevs.tweet.each do |tweeters| %>
        <li><%= tweeters.description %> 
            | <%= link_to "Show", controller: "tweets", action: "show", id: tweeters.id   %> 
            <% if user_signed_in? %>
                <% if current_user.id == tweeters.user_id %>
                    | <%= link_to 'Edit', edit_tweet_path(tweeters.id) %> 
                    | <%= link_to 'Destroy', tweet_path(tweeters.id), method: :delete, data: { confirm: 'Are you sure?' } %> |
                <% end %>
            <% end %>
        </li>
    <% end %>
</ul>    

<br/>

app/views/home/users.html.erb
<h1>List Users</h1>

<% @users.each do |person| %>
    <br/><br/>
    <a href="/<%= person.user_name %>">@<%= person.user_name %></a> <% person.email %> <% person.id %>
    <br/>
    <ul>
    <% person.tweet.each do |tweets| %>
        <li><%= tweets.description %></li> 
    <% end %>    
    
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "home/nav" %>


<div class="container">
  <%= render "home/flash_alerts" %>
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% f.label :description, "Tweet it!" %><br>
    <%= f.text_area :description, size: "150", class: 'form-control' %>
  </div>
  <div class="form-group">
    <% f.label :user_id %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Post Tweet", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
    <% @tweets.order("created_at desc").each do |tweet| %>
      
      
        
            <% @namer.each do |stuff| %>
              <% if tweet.user_id == stuff.id %>
                <div class="panel panel-default">
                  
                  <div class="panel-body">
            
      
      <%= tweet.description %>            
    </div>
          <% tweet.user_id %>
        <div class="panel-footer">
          <a href="/<%= stuff.user_name %>">@<%= stuff.user_name %></a>
          <% link_to 'Show', tweet %>
          <% link_to 'Edit', edit_tweet_path(tweet) %>
          <% link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
</div>
<br/><br/>
            <% end %>
          <% end %>
    <% end %>

app/views/tweets/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Tweet</h3>
  </div>
  <div class="panel-body">

        <%= render 'form' %>


    </div>
    <div class="panel-footer"><%= link_to 'Back', tweets_path %></div>
</div>

app/views/tweets/show.html.erb
<p>
  <strong>Tweeter:</strong>
  
  <%= @tweet.description %>
</p>

<p>
  <strong>Users:</strong>

<% @tweet.user_id %>
  <% @namer.each do |x| %>
    <% if x.id == @tweet.user_id %>
      <a href="/<%= x.user_name %>">@<%= x.user_name %></a>
    
</p>
    <% if user_signed_in? %>
      <% if current_user.id == @tweet.user_id %>
        <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
        <%= link_to 'Destroy', tweet_path(@tweet), method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
    <% end %>
  <% end %>
<% end %>
<%= link_to 'Back', tweets_path %>